ARG BASE_IMAGE="ska-build:0.1.2"
FROM $BASE_IMAGE

LABEL int.skao.image.team="Systems Team" \
    int.skao.image.url="https://gitlab.com/ska-telescope/ska-base-image" \
    int.skao.image.source="images/ska-build-python/Dockerfile" 

COPY skao.metadata /etc/skao.metadata 

CMD ["bash"]
